train_dir: data/train_medium
val_dir: data/val_full
test_dir: data/test_full
out_dir: results

cuda: True
gpu_ids: [0]

batchsize: 1
test_batchsize: 1
epoch: 20
size: 256
threads: 4

lr: 0.0002
beta1: 0.5
lamb: 100
minimax: 1

gen_model: unet
gen_init: 
dis_init: 
in_ch: 3
out_ch: 3

manualSeed: 0
snapshot_interval: 4
